menu:
  home: { id: index, url: / }
  arch: { id: archives, url: /archives }
  tags: { id: tags, url: /tags }
  cat: { id: categories, url: /categories }
  cv: { id: curriculumvitae, url: /curriculumvitae }
  links: { id: links, url: /links }

github: YOUR_GITHUB_NAME

background-root: /images/background/
background: [ 1.jpg, 2.jpg, 3.jpg ]

avatar: /images/avatar.png

#### Comment
disqus_shortname: YOUR_DISQUS_SHORT_NAME    ## disqus short name.


rss: YOUR_RSS_ADDRESS                    ## if any...
